server:
  port: 8080
  context-path: /spider
#logging:
#  file: mylog.log
# path: E:\log

spring:
    datasource:
        name: test
        url: jdbc:mysql://47.105.159.172:3306/test?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.carwel.webmagic.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    # reasonable 为false 超过页数返回空
    reasonable: false   
    supportMethodsArguments: true
    params: count=countSql

apache:
  rocketmq:
    consumer:
      spiderConsumerGroup: spiderConsumerGroup
    producer:
      spiderproducerGroup: spiderProducerGroup
    namesrvAddr: 47.105.159.172:9876
    topic:
      spider_topic: webmagic-spider
redis:
  host: 47.105.159.172
  port: 6379
  timeout: 300
  password: 123456
  poolMaxTotal: 10
  poolMaxIdle: 10
  poolMaxWait: 3
